### ISSUE TITLE
Kansas soil sanity check

### ISSUE THREAD

**Issue by CamiloPosso** [microbiomedata/kaiko_metaproteome#11]
Track down the other 3 datasets from the Kansas soil benchmark (25ug_hits, 100ug_hits, WD_pool_hits) and run the pipeline with these.

**Comment by CamiloPosso** [comment]
Joon had placed all 4 datasets on DMS. Will use the already converted mzml files with Kaiko.

Also have the script which produced the Kaiko Kansas soil phylum counts to compare.

**Comment by CamiloPosso** [comment]
Ran all 4 datasets, the same top taxa are identified as in the 2020 run, but the number of hits are reduced by about 25%. Further investigating why.

DIAMOND parameters greatly affect the total number of 100% alignments we find after denovo inference. A fast search finds 10% of the 100% hits that the default DIAMOND parameters can find. This is likely the cause of reduced number of taxa hits when compared to the Kansas soil 2020 numbers, since phylum makeup of the taxa identified is very similar.

**Comment by ssarrafan** [comment]
@CamiloPosso I'm adding this to the current sprint. Let me know if you're not working on it. Thanks!

**Comment by ssarrafan** [comment]
@CamiloPosso @pdpiehowski what's the status of this issue?  is it actively being worked on?

**Comment by CamiloPosso** [comment]
I just finished this one yesterday, with the benchmark numbers agreeing with what we expected from the 2020 runs. I updated the benchmark ppt in the teams files
