### ISSUE TITLE
Finish implementation of UniprotKB database in Kaiko

### ISSUE THREAD

**Issue by CamiloPosso** [microbiomedata/kaiko_metaproteome#16]

**Comment by ssarrafan** [comment]
@CamiloPosso what's the status of this issue?  I'm changing it to backlog since I don't see any updates since Oct.  Let me know. Thanks.

@pdpiehowski

**Comment by ssarrafan** [comment]
Over a year old. Any updates? Can this be closed? @CamiloPosso @pdpiehowski @lamccue

**Comment by lamccue** [comment]
I believe this is done. @CamiloPosso please confirm.

**Comment by CamiloPosso** [comment]
Yes this is done. We decided to use the Reference Proteomes and that has been implemented.
