### ISSUE TITLE
Improve logic behind taxa scoring an FASTA aggregation

### ISSUE THREAD

**Issue by CamiloPosso** [microbiomedata/kaiko_metaproteome#3]
Currently the taxa -> FASTA logic is rough around the edges. 

Main goal is lower FASTA size, while keeping accurate taxa identification. Taxa identification looks good, but the FASTAs are huge.

**Comment by ssarrafan** [comment]
@CamiloPosso are you actively working on this issue?  I will move it to the current sprint but let me know if you're not working on it. Thanks.

**Comment by CamiloPosso** [comment]
@ssarrafan Yes I'm working on this one right now.

**Comment by ssarrafan** [comment]
@CamiloPosso any update on this issue?  Still active?

**Comment by CamiloPosso** [comment]
Improved FASTA aggregation and released as Kaiko 1.0 #8
